# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Ogh+mQRgfwozxSkMv7z9S0+VVI0R7OP/heGUTBBJZRXoAsIMBQDOHALxhpYuP1g9Xn2WP/onGQo12aF6oW48lthorBu3bdHa5dW6b2q0ucu5q7DGSJpc1Cm60XTVJgy87Y3iPY04HqI7i2ZDSTQtOAdSFDqPz+34TaUiIDQGdteBTPXeX9XfBvygp9Wy+tz36k4CO0abrS1iIWlOuhqOOz9eXAy2S3GqF8LhNMQwgG8F5nGcCVWDz8aAFJ9IH18VB6doViE0hnyI9P0QMETOnwOenLjaTfPmG1eiEgSrJDAgTm/NjVTilRLKEhJ88dRvrOiyUdb9MtnU4eyqcu41oF5qGWUSgI1EI/4W9huyuFteT89+4qe+7Y0tm0lc2b/rTt//UoEaPETomvgst4KqnozAjXa5++5ygXgxEhsHD68TMWEipFXTipGeGX0SE1RDF84UrlvtxaZyLFDXoeAuRe8QiA41zplkTuH419xpl++VkqzsKL5qY5a/wEaaxXW506KrwA344c6UdKEPn8LIVWaCMepMTigSOdQH2C/BE+HfNKjfizlbEgJ447NE3kaH51xRxlsL4xOw0aJzYI0HueFIs7RXf64vElNQO6XePvytUt4F7AuMkkZyfnjA8Iw5V0C2M+ENdsXMii3ImUcmtTucaykbWRmMGQS/6ddfXxA="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
